### ISSUE TITLE
[camerarawpreviews] Fout: Exception: Unable to find preview data: 

### ISSUE THREAD

**Issue by Piefje01** [ariselseng/camerarawpreviews#101]
This happend most on TIFF files and/or in a groupmap

Nextcloud AIO.

[camerarawpreviews] Fout: Exception: Unable to find preview data: /var/www/html/custom_apps/camerarawpreviews/vendor/exiftool/exiftool/exiftool.bin -json -preview:all -FileType '/mnt/ncdata/__groupfolders/1/Subfolder_001/IJking_IJking_000065.tif' -> [{
  "SourceFile": "/mnt/ncdata/__groupfolders/1/Subfolder_001/IJking_IJking_000065.tif",
  "FileType": "TIFF"
}]
 at <<closure>>

 0. /var/www/html/custom_apps/camerarawpreviews/lib/RawPreviewBase.php line 110
    OCA\CameraRawPreviews\RawPreviewBase->getBestPreviewTag("/mnt/ncdata/__g ... f")
 1. /var/www/html/custom_apps/camerarawpreviews/lib/RawPreviewBase.php line 60
    OCA\CameraRawPreviews\RawPreviewBase->getResizedPreview("/mnt/ncdata/__g ... f", 2048, 2048)
 2. /var/www/html/custom_apps/camerarawpreviews/lib/RawPreviewIProviderV2.php line 25
    OCA\CameraRawPreviews\RawPreviewBase->getThumbnailInternal(["OC\\Files\\Node\\File"], 2048, 2048)
 3. /var/www/html/lib/private/Preview/GeneratorHelper.php line 64
    OCA\CameraRawPreviews\RawPreviewIProviderV2->getThumbnail(["OC\\Files\\Node\\File"], 2048, 2048)
 4. /var/www/html/lib/private/Preview/Generator.php line 361
    OC\Preview\GeneratorHelper->getThumbnail(["OCA\\CameraRaw ... "], ["OC\\Files\\Node\\File"], 2048, 2048)
 5. /var/www/html/lib/private/Preview/Generator.php line 337
    OC\Preview\Generator->generateProviderPreview(["OC\\Files\\SimpleFS\\SimpleFolder"], ["OC\\Files\\Node\\File"], 2048, 2048, false, true, "image/x-dcraw", "")
 6. /var/www/html/lib/private/Preview/Generator.php line 149
    OC\Preview\Generator->getMaxPreview(["OC\\Files\\SimpleFS\\SimpleFolder"], [], ["OC\\Files\\Node\\File"], "image/x-dcraw", "")
 7. /var/www/html/lib/private/Preview/Generator.php line 116
    OC\Preview\Generator->generatePreviews(["OC\\Files\\Node\\File"], [[250,250,true,"fill"]], "image/x-dcraw")
 8. /var/www/html/lib/private/PreviewManager.php line 192
    OC\Preview\Generator->getPreview(["OC\\Files\\Node\\File"], 250, 250, true, "fill", null)
 9. /var/www/html/core/Controller/PreviewController.php line 144
    OC\PreviewManager->getPreview(["OC\\Files\\Node\\File"], 250, 250, true, "fill")
10. /var/www/html/core/Controller/PreviewController.php line 113
    OC\Core\Controller\PreviewController->fetchPreview(["OC\\Files\\Node\\File"], 250, 250, false, false, "fill")
11. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OC\Core\Controller\PreviewController->getPreviewByFileId(755548, 250, 250, false, false, "fill")
12. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OC\\Core\\Cont ... "], "getPreviewByFileId")
13. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OC\\Core\\Cont ... "], "getPreviewByFileId")
14. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OC\\Core\\Controller\\PreviewController", "getPreviewByFileId", ["OC\\AppFramewo ... "], ["core.Preview.getPreviewByFileId"])
15. /var/www/html/lib/base.php line 1068
    OC\Route\Router->match("/core/preview")
16. /var/www/html/index.php line 36
    OC::handleRequest()

**Comment by ariselseng** [comment]
That exception is meant as a warning/info. It just means that the files do not contain an embedded preview. If you had installed imagick then TIFF preview could be generated, though.

I might add a better error message for these cases.
