### ISSUE TITLE
Cannot open raw file in NC 28

### ISSUE THREAD

**Issue by faznam** [ariselseng/camerarawpreviews#102]
I can't open a raw file. In the file list view, the browser downloads the raw file directly, and in the grid view, clicking on a file does nothing at all.
However, the thumbnails are generated and displayed correctly.

Infos :
Camera RAW Previews 0.8.4
Nextcloud 28.0.1

**Comment by ikocev** [comment]
+1

**Comment by berveles** [comment]
Similar situation

**Comment by eatgrass** [comment]
same

**Comment by sebastianfru** [comment]
Same

**Comment by ariselseng** [comment]
This is a duplicate of this one: https://github.com/ariselseng/camerarawpreviews/issues/99
