### ISSUE TITLE
All DNG files without embedded previews result in ERRORS in the logfile.

### ISSUE THREAD

**Issue by dimension128** [ariselseng/camerarawpreviews#103]
I understand that this doesn't hurt anything. However this does leave a rather bothersome warning in nextclouds admin-> overview page. Example: `There are some warnings regarding your setup. 111 errors in the logs since April 15, 2024`
Could you please change the "Unable to find preview data: " message to to loglevel - WARN (2),  instead of the current ERROR (3)?

**Comment by ariselseng** [comment]
I agree. This should be at most a warning, if not something less than that. 
PRs are welcome.

**Comment by ariselseng** [comment]
Fixed in v0.8.5. Does it help?
