### ISSUE TITLE
0.8.5 update seems to break preview on Nextcloud 28

### ISSUE THREAD

**Issue by helloha82** [ariselseng/camerarawpreviews#105]
Just updated to 0.8.5 with an update to NC29 in mind but decided to hold off until the next NC dot release.

Now 0.8.5 does not seem to work with NC28 anymore?

**Comment by ariselseng** [comment]
Which php are you running?

**Comment by plaes** [comment]
I'm also seeing some issue with nextcloud 29.0.1 + camerarawpreviews-0.8.5, firstly there's a JS error in console:
```
The handler doesn't have a valid component 
Object { id: "camerarawpreviews", mimesAliases: {…} }
id: "camerarawpreviews"
​mimesAliases: Object { "image/x-dcraw": "image/jpeg" }
​​"image/x-dcraw": "image/jpeg"
...
```
PHP version is 8.2.18 (Debian stable)

**Comment by helloha82** [comment]
> Which php are you running?

This one:



Version: 8.1.28

Memory limit: 10 GB

Max execution time: 3600

Upload max size: 9,8 GB

OPcache Revalidate Frequency: 2

Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Comment by helloha82** [comment]
> Which php are you running?

`

Version: 8.1.28

Memory limit: 10 GB

Max execution time: 3600

Upload max size: 9,8 GB

OPcache Revalidate Frequency: 2

Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
`

**Comment by helloha82** [comment]
> Which php are you running?

> 

Version: 8.1.28

Memory limit: 10 GB

Max execution time: 3600

Upload max size: 9,8 GB

OPcache Revalidate Frequency: 2

Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Comment by ariselseng** [comment]
> I'm also seeing some issue with nextcloud 29.0.1 + camerarawpreviews-0.8.5, firstly there's a JS error in console:
> 
> ```
> The handler doesn't have a valid component 
> Object { id: "camerarawpreviews", mimesAliases: {…} }
> id: "camerarawpreviews"
> ​mimesAliases: Object { "image/x-dcraw": "image/jpeg" }
> ​​"image/x-dcraw": "image/jpeg"
> ...
> registerHandler https://SERVER/apps/viewer/js/viewer-main.mjs?v=b0d516dd-4:2187
>     <anonymous> https://SERVER/apps/camerarawpreviews/js/register-viewer.js?v=b0d516dd-4:2
> ```
> 
> PHP version is 8.2.18 (Debian stable)

This has been broken in Nextcloud Viewer for years now. The problem is upstream. There is pending PR's which never merges.

**Comment by ariselseng** [comment]
> > Which php are you running?
> 
> > 
> 
> Version: 8.1.28
> 
> Memory limit: 10 GB
> 
> Max execution time: 3600
> 
> Upload max size: 9,8 GB
> 
> OPcache Revalidate Frequency: 2
> 
> Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Seems okay. Are you talking about actual previews ( small thumbnails in the file manager) or are you talking about not able to open raw files with the Viewer app?

**Comment by helloha82** [comment]
> > > Which php are you running?
> > 
> > 
> > > 
> > 
> > 
> > Version: 8.1.28
> > Memory limit: 10 GB
> > Max execution time: 3600
> > Upload max size: 9,8 GB
> > OPcache Revalidate Frequency: 2
> > Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
> 
> Seems okay. Are you talking about actual previews ( small thumbnails in the file manager) or are you talking about not able to open raw files with the Viewer app?

The thumbnails are fine, it's when you open an image it just suggest a download instead of a preview.

**Comment by ariselseng** [comment]
See https://github.com/ariselseng/camerarawpreviews/issues/86
This is not a new issue.
