### ISSUE TITLE
RAW Previews Icons Working but when clicking Downloading Image Instead of Showing Large Preview

### ISSUE THREAD

**Issue by sebastianfru** [ariselseng/camerarawpreviews#106]
The problem is described in the title.
I have Nextcloud 29.0.1, but the problem started with Nextcloud 28.

Instead of opening a preview when clicking a RAW photo, it downloads the file.

A little workaround:
The only way I can see a preview is when I have a JPG file in the same folder. I open the JPG that shows the preview, then go to the next image. In that case, I can see the RAW files.
However, this is very inconvenient.

**Comment by ariselseng** [comment]
@sebastianfru This problem needs to be adressed in the Nextcloud Viewer. See also: https://github.com/ariselseng/camerarawpreviews/issues/86
