### ISSUE TITLE
Error 500 Call to undefined function OCA\\CameraRawPreviews\\shell_exec() in file '/var/lib/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php' line 144

### ISSUE THREAD

**Issue by GargamelCZ** [ariselseng/camerarawpreviews#107]
CameraRawPreviews doesn't generate any previews at all, any attempt just leads to error 500.

~ # occ -V
Nextcloud 29.0.3

~ # tail -n1 /var/log/nextcloud/nextcloud.log
{"reqId":"WTg5n0db02gjJXSrkJ3R","level":3,"time":"July 17, 2024 05:40:50","remoteAddr":"192.168.1.4","user":"Pavel","app":"index","method":"GET","url":"/index.php/core/preview?fileId=585&x=128&y=128&mimeFallback=true&a=0","message":"Call to undefined function OCA\\CameraRawPreviews\\shell_exec() in file '/var/lib/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php' line 144","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","version":"29.0.3.4","exception":{"Exception":"Exception","Message":"Call to undefined function OCA\\CameraRawPreviews\\shell_exec() in file '/var/lib/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php' line 144","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/webapps/nextcloud/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":170,"Previous":{"Exception":"Error","Message":"Call to undefined function OCA\\CameraRawPreviews\\shell_exec()","Code":0,"Trace":[{"file":"/var/lib/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php","line":62,"function":"getBestPreviewTag","class":"OCA\\CameraRawPreviews\\RawPreviewBase","type":"->"},{"file":"/var/lib/nextcloud/apps/camerarawpreviews/lib/RawPreviewIProviderV2.php","line":25,"function":"getThumbnailInternal","class":"OCA\\CameraRawPreviews\\RawPreviewBase","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Preview/GeneratorHelper.php","line":64,"function":"getThumbnail","class":"OCA\\CameraRawPreviews\\RawPreviewIProviderV2","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Preview/Generator.php","line":361,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Preview/Generator.php","line":337,"function":"generateProviderPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Preview/Generator.php","line":143,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Preview/Generator.php","line":110,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/PreviewManager.php","line":187,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/usr/share/webapps/nextcloud/core/Controller/PreviewController.php","line":174,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/usr/share/webapps/nextcloud/core/Controller/PreviewController.php","line":142,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/webapps/nextcloud/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/lib/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php","Line":144},"message":"Call to undefined function OCA\\CameraRawPreviews\\shell_exec() in file '/var/lib/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php' line 144","exception":{},"CustomMessage":"Call to undefined function OCA\\CameraRawPreviews\\shell_exec() in file '/var/lib/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php' line 144"}}

**Comment by ariselseng** [comment]
Your web host has disabled use of shell_exec which is a hard requirement of this app. I am sorry.
