### ISSUE TITLE
Adding support for .CR3 files

### ISSUE THREAD

**Issue by KasaTheWolf** [ariselseng/camerarawpreviews#110]
Currently only .CR2 files are supported. It would be awesome to add the compatibility to .CR3 files.

**Comment by cptechie** [comment]
Hey there @KasaTheWolf! Did you get this to work? I am also not able to see my CR3 files.

**Comment by cptechie** [comment]
> Hey there @KasaTheWolf! Did you get this to work? I am also not able to see my CR3 files.

Disregard. Should have read through the other issues first.
