### ISSUE TITLE
[Question] How to configure preview resolution?

### ISSUE THREAD

**Issue by opalek84** [ariselseng/camerarawpreviews#112]
How to setup resolution for RAW previews? I have preview_max_x/y props set as 1024 and normal jpeg files are generated as 1024, but RAW previews are generated as 640x480.
How can I change it?

**Comment by ariselseng** [comment]
There is no preview generation here. Only extraction. So your embedded previews are probably 640x480.

**Comment by opalek84** [comment]
@ariselseng thank you for your answer, so I will check settings one again, this is strange because other previews are in 1024... maybe there is some conflict with memories add-on.

**Comment by ariselseng** [comment]
My app only extracts previews and does not upscale, only downscales. That can explain it.
