### ISSUE TITLE
updating in nextcloud 17

### ISSUE THREAD

**Issue by ThomasVermeersch** [ariselseng/camerarawpreviews#36]
when I try to update to version 7.1 of camerarawpreviews, it tries to download the wrong github link.

nextcloud log containing the unavailable package link: 
{"Exception":"GuzzleHttp\\Exception\\ClientException","Message":"Client error: `GET https://github.com/ariselseng/camerarawpreviews/releases/download/v0.7.1/camerarawpreviews_nextcloud.tar.gz`

 this is the one it should point to:
https://codeload.github.com/ariselseng/camerarawpreviews/tar.gz/v0.7.1

**Comment by ariselseng** [comment]
I am sorry I had to remove the asset due to a breaking bug in the release. I couldn't figure out how to remove the update from apps.nextcloud.com before I needed to go to work. I will push a fix as soon as I can.

**Comment by ThomasVermeersch** [comment]
Ow no it's fine man, I was just trying to help out! You are doing a great
job with the app by the way!!

Greetings,

Thomas

**Comment by ariselseng** [comment]
@ThomasVermeersch Thank you. I have pushed a new release now that fixes the borked release.
