### ISSUE TITLE
perl warning with dockerized nextcloud

### ISSUE THREAD

**Issue by husdo** [ariselseng/camerarawpreviews#38]
With nextcloud 17.0.1 I get the following warning messages: "You do not have perl globally installed. Using a deprecated built in perl."

**Comment by ariselseng** [comment]
That means your docker image does not have perl installed and the app is using a old bundled version instead. I introduced this logging because I want to remove the bundled perl in an upcoming release. But I should have mentioned this in the readme.

**Comment by D34DC3N73R** [comment]
Is there any update on this? My logs are full of this and it makes it hard to see any other relevant warnings.

**Comment by ariselseng** [comment]
You need to use a docker image that have perl installed. That is the way to solve this.

**Comment by D34DC3N73R** [comment]
Thanks. For anyone else that runs across this issue while using the LSIO nextcloud image, it's possible to install perl yourself using custom scripts https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
