### ISSUE TITLE
No preview and Message "Error with loading XXXX.cr2"

### ISSUE THREAD

**Issue by FlokMD** [ariselseng/camerarawpreviews#42]
Hy I´m using the Nextcloud as Storage for my pictures. With the new Version 18.0.4 I only get the message "Error with loading..." or in german "Fehler beim Laden" if I want to have a preview of any .cr2.

There is no Log entry or anything else...

Thanks for the help

**Comment by ariselseng** [comment]
What kind of server do you use?  How is nextcloud installed? Do you use a unofficial docker image or maybe the snap?

**Comment by trispembo** [comment]
Hi there, I have the the same problem. The preview function has never worked on my installation.

I'm using VirtualBox snap installation. Everything else on the sever is working fine - and has for over a year - except for the camera preview app.

**Comment by ariselseng** [comment]
I have not gotten around to supporting snaps. I am not sure it is actually possible without editing the snap image I am afraid. If somebody wants to track this down I would be grateful.

**Comment by trispembo** [comment]
Ah ha, that explains it. Thanks for the update.

**Comment by ariselseng** [comment]
@trispembo I just tried the latest snap (19.0.1snap1) and just worked out of the box. Could you try this again with the absolute latest snap, to be sure?

**Comment by trispembo** [comment]
Hey Ari,

Still not working for me. I removed the app, re-downloaded through the app store and activated. Still not working. My current install is Nextcloud 19.0.1 (snap).

**Comment by ariselseng** [comment]
Could you send me an example file that does not work?

**Comment by trispembo** [comment]
Hey Ari, there're four RAW files from four different camera here:
https://u.pcloud.link/publink/show?code=kZtnEakZQsTfWltjhFSmGfErcShBqmCWJSi7

These are all the cameras that I own that produce RAW files.  
All of them are failing to generate previews.

Canon 5D mkII
FujiFilm X-100
FujiFilm X-Pro1
FujiFilm X-T1

**Comment by ariselseng** [comment]
@trisembo all four of these files worked fine for me. The preview output is cached, even if it failed it will cache the failed result. Have you tried a new file (you can upload an old file with a new file name) since you latest version of both nextcloud snap and the app?

**Comment by trispembo** [comment]
Each of those files are old files I re-named and re-uploaded. All failed to generate previews.

**Comment by ariselseng** [comment]
@trisembo do you see anything in the logs relates to this?

**Comment by trispembo** [comment]
Maybe this...

"level":3,"time":"2020-07-28T06:26:28+00:00","remoteAddr”:”**.**.***.**”,”user”:”*****”,”app":"PHP","method":"GET","url":"/index.php/apps/audioplayer/setvalue?type=category&value=Artist-154-2360-150","message":"Undefined index: host at /var/snap/nextcloud/22400/nextcloud/extra-apps/bbb/appinfo/app.php#12","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36","version":"19.0.1.1"}

**Comment by ariselseng** [comment]
@trispembo no this is unrelated.
I am willing to debug this if you can provide me with a tmate/ssh session or just teamviewer.

**Comment by trispembo** [comment]
Thanks Ari, I'm open to that. Just need to find a way to do it securely.

**Comment by ariselseng** [comment]
You can also make a minimal virtualbox image that has the problem and then you can send me disk image. If you will that is safer/easier.

**Comment by trispembo** [comment]
NextCloud is already running as an appliance on VirtualBox. I'm open for a teamviwer/screen sharing approach, but what is it you'll need to look at apart from logs?

**Comment by ariselseng** [comment]
I will want to open an text editor and add some debugging code to the camerarawpreviews files. So that when things don't work we can get more helpful logging. Now there is limited help with the logs I am afraid.

**Comment by trispembo** [comment]
So if I could share my screen when logged into terminal - and have an audio call at the same time - then you could talk me through what's needed? Would that work? Or you give me instructions on how to add de-bug code, and then share the logs?

I'm not an IT professional, just a tinkerer, but can usually follow instructions.

**Comment by ariselseng** [comment]
@trispembo I installed a vm with Ubuntu 18.04 and then installed the nextcloud snap now. There seems to be some apparmor issues. There is no point right now to debug on you machine as I thought at first.
You can follow the issue here if you want: https://github.com/nextcloud/nextcloud-snap/issues/1422

**Comment by trispembo** [comment]
Thanks for the update Ari.

**Comment by ariselseng** [comment]
@trispembo I have pushed a new update of my app that hopefully fixes your issue. Can you try the lastest update? You need to reupload a raw file with a new name or location to be sure if works or not.

**Comment by trispembo** [comment]
Awesome Ari, that's fixed it. 

I didn't need to re-upload or change the name of the RAW files, it's now working as expected. It's really a useful function for me as I have thousands of RAW files and that saves me from having to convert them into jpeg to be able to preview through the NextCloud GUI.

Great work! I really appreciate you taking the time to sort it out.
