### ISSUE TITLE
Feature Request: Canon CR3 RAW support

### ISSUE THREAD

**Issue by arcotek-ltd** [ariselseng/camerarawpreviews#43]
Apologies if it already works - Google hasn't returned any results and I'm reluctant to install NextCloud without this requirement.

As the title suggests, please add support for Canon CR3 RAW image files.

Thanks

**Comment by ariselseng** [comment]
@arcotek-ltd
CR3 is whitelisted and active, but it all relies on the files having embedded exif previews (most have).
This app uses exiftool to extract previews. If exiftool can find a preview embedded in the file then yes it will work.

If you have exiftool installed you can test if there is any previews with your files with this command:
`exiftool -json -preview:all FILENAME.CR3`
