### ISSUE TITLE
Please update for Nextcloud 19

### ISSUE THREAD

**Issue by owerg** [ariselseng/camerarawpreviews#44]
Please update the config so that it will work w/version 19

**Comment by Derridaralalala** [comment]
@ariselseng Agree. Need it for workflows, it`s an awesome NC App! Please update for NC :-)

**Comment by ariselseng** [comment]
Fixed with latest release.

**Comment by Tahvok** [comment]
@ariselseng I have 0.7.4 however it still says:
```
    This app cannot be installed because the following dependencies are not fulfilled:
        Server version 18 or lower is required. 
```

**Comment by ariselseng** [comment]
@Tahvok That must be some kind of caching issue. It definitely works on Nextcloud 19.
