### ISSUE TITLE
Staticperl flagged as trojan

### ISSUE THREAD

**Issue by expiredemulsion** [ariselseng/camerarawpreviews#45]
It appears as the staticperl from camerarawpreviews is being flagged as a trojan by some EPP.
/var/snap/nextcloud/22327/nextcloud/extra-apps/camerarawpreviews/bin/staticperl

https://www.virustotal.com/gui/file/b6cdc997acdcad95a60c343e90dc5fb8c02f8e9c22642a9676c9aa3b3dc6ebc1/details 

Perhaps it might be of interest to take a look at it.

**Comment by ariselseng** [comment]
@expiredemulsion thank you. This is just a false positive. Many trojans use an embedded Perl and that is why it is finding it.
That being said I am planning to remove it as it is quite old.

**Comment by ariselseng** [comment]
@expiredemulsion I have released a new version which removes this executeable. It was always something I wanted to remove as it was old and updated. This report made me do it.
Again, it is just a false positive, but I do not want people to think there is a trojan in their server :D

Thank you again.
