### ISSUE TITLE
Won't load in version

### ISSUE THREAD

**Issue by GitBoxer** [ariselseng/camerarawpreviews#46]
After updating to 18.0.7 web installer I get "This app cannot be installed because the following dependencies are not fulfilled:
The command line tool perl could not be found"

**Comment by ariselseng** [comment]
Yes. Perl is a hard dependency now. In earlier versions I logged that the app was using a legacy bundled Perl binary and now it's finally gone.

**Comment by ariselseng** [comment]
@GitBoxer I am sorry for this. If you are able to install perl on your server it can be installed. Closing.
