### ISSUE TITLE
randomly stopped working 

### ISSUE THREAD

**Issue by rebel22lax** [ariselseng/camerarawpreviews#47]
I cant reinstall either, getting the error 

This app cannot be installed because the following dependencies are not fulfilled:
The command line tool perl could not be found

I'm on the latest stable version of nextcloud

**Comment by ariselseng** [comment]
Perl is now a requirement. I am sorry. But it has to do with maintenance and security.

**Comment by rebel22lax** [comment]
is there a link or document on how I can install perl?

**Comment by ariselseng** [comment]
What OS/platform are you running Nextcloud on? If you have Ubuntu or another Debian-based distro, you can do it with "sudo apt-get install perl".
Most linux distros have perl already installed so in usually there is nothing you need to do.

**Comment by rebel22lax** [comment]
I'm on an unraid server that I built so I'm using their next cloud docker 

as far as sudo goes can I just use the terminal inside unraid to run the command?

![image](https://user-images.githubusercontent.com/16298084/88701039-7e13e300-d0d7-11ea-894f-2ac7d2ad6b1d.png)

**Comment by ariselseng** [comment]
@rebel22lax  If you are using docker then I would suggest you use the [official nextcloud image](https://hub.docker.com/_/nextcloud?tab=tags) as that has perl built-in.

If you really want to use your existing container you can run "apt-get update && apt-get install perl" inside the docker container but you will loose those changes whenever the container is recreated...

**Comment by rebel22lax** [comment]
so after doing my googles I learned that for the unraid nextcloud docker I needed to be using apk 

so using my limited terminal knowledge I came across the right command line which is 

sudo apk add perl  

![image](https://user-images.githubusercontent.com/16298084/88705200-31330b00-d0dd-11ea-89fd-25c90a24b4b6.png)

I then logged into my next cloud and was able to enable the camera raw plugin and it works so thank you @ariselseng together we got it done and I hope this helps anyone else like me.


![image](https://user-images.githubusercontent.com/16298084/88705405-79eac400-d0dd-11ea-9c36-49569367e8d4.png)

**Comment by ariselseng** [comment]
@rebel22lax Good you got it going. Just a reminder: If you upgrade/recreate the docker container you will loose your changes.
I strongly recommend using the official nextcloud container.

**Comment by rebel22lax** [comment]
@ariselseng I'm not sure how I tie that into my unraid system. because sometimes unraid will say nextcloud has an update or I can log into nextcloud itself and see that there is an upgrade which I did today.  So is it as easy as running "sudo apk upgrade update" ? and I wont have to worry in the future

![image](https://user-images.githubusercontent.com/16298084/88706279-a4894c80-d0de-11ea-95df-686918be2f25.png)

**Comment by ariselseng** [comment]
No I do not think it does work like that.
If unraid is making a new nextcloud image (which I think it does) perl will need to be reinstalled every time.
You cannot upgrade nextcloud with apk.

I recommend you use the official docker image or you ask the maintainer of the the unraid one to include perl for new releases.
