### ISSUE TITLE
The app is not working

### ISSUE THREAD

**Issue by claublog** [ariselseng/camerarawpreviews#48]
Hi,

I'm running the snap version of nextcloud 19.0.1 in an Ubuntu 18.04 LTS.
The app is installed and activated, but it's not working. The .CR2 files are supposed to be previewed. Even clicking on them doesn't display the image.

Neither it does in the Android app.

Can someone please help me to troubleshoot it? In Nextcloud's register there are no messages related to the Camera RAW previews

**Comment by ariselseng** [comment]
The very first thing I want is for you to send me an example file that does not work. I can test it in my installation to be sure the file actually has previews embedded.

Also, there have been lots of people reporting issues when using the snap version of nextcloud, even though I haven't been able to reproduce it. It might be to something called apparmor, which I haven't tested yet that I think snapd on Ubuntu has enabled.

If you can, using Nextcloud with the official Nextcloud docker image will make it work. That is what I personally use.

**Comment by ariselseng** [comment]
@claublog can you retry with the latest update?

**Comment by claublog** [comment]
Hi @ariselseng,

Thank you very much for your support.
Updating to 0.7.6 fixed the issue.

Best regards
