### ISSUE TITLE
CPU overloading on opening large photo folder

### ISSUE THREAD

**Issue by z28rbill** [ariselseng/camerarawpreviews#49]
Hi !

Tonight I opened a folder with ~100 photos of 32MB each. The total folder is around 3.2GB.
The server went unreachable few minutes after. I needed to hard reboot it

Nextcloud version : 19.0.1 Dockerized
Application version : 0.7.4
**File format : .CR2**
I don't know if it's important, but the folder is a shared folder

**The first analysis show a CPU overconsumption :**

![image](https://user-images.githubusercontent.com/46965128/88981553-80885f80-d2c6-11ea-87aa-df7fd35f62a1.png)

![image](https://user-images.githubusercontent.com/46965128/88981584-9007a880-d2c6-11ea-87ad-f4dfc81dcdf3.png)

100 load avg 1 :boom: _I've only two cores on this server_ 

And the responsible is the apache2 process.

**From 22 processes to 114.**

![image](https://user-images.githubusercontent.com/46965128/88981986-79ae1c80-d2c7-11ea-91be-2ae95c07ec38.png)

Without further reading on your application's code, i guess that maybe the lazyloading is not implemented and on the folder open, it tried to load previsualization of the whole folder ?

**Comment by ariselseng** [comment]
@z28rbill Hi,
This is a flaw in Nextcloud and not something I can fix in my app. I think it is lazyloaded some parts in Nextcloud but not everywhere. Also the amount of concurrent preview generations should be configureable. A Raspberry pi will choke.

As a work-around you can pre-generate previews with the previewgenerator app.

**Comment by ariselseng** [comment]
@z28rbill Can you try the lastest version of the app? I think maybe it is a little faster. Not that it fixes the concurrency problem though.
