### ISSUE TITLE
0.7.6 - exiftool.bin testet positive for virus! - Backdoor.Linux.bskw

### ISSUE THREAD

**Issue by TauNeutrino** [ariselseng/camerarawpreviews#50]
Hi,
I updated the app on my nextcloud yesterday and just got the message that the file /vendor/exiftool/exiftool/exiftool.bin
testet positive for a fairly new linux virus: Backdoor.Linux.bskw

https://www.virustotal.com/gui/file/879d6b4b6203b411731fc35c2b74abd8740f39dcaa694d494d204f54b475d6d9/detection
I sincerely hope this is a false positive but nevertheless I have to take actions...

I would suggest to update your app with a clean file asap!

Best

**Comment by ariselseng** [comment]
@TauNeutrino It is 100% a false positive. I have built the binary my self.

**Comment by ariselseng** [comment]
@TauNeutrino You can check how it is done inside the build/tools folder.

**Comment by TauNeutrino** [comment]
Thanks for clarification.
I will watch my system closely though.

**Comment by ariselseng** [comment]
@TauNeutrino I am using a well known compressor called "upx". to make the binary about 60% smaller. It is the upx signature that can cause a false positive. I will try later to add some flags to make it go "under the radar". If you google upx and virustotal you see that there is lots of false positives.

**Comment by ariselseng** [comment]
@TauNeutrino I have now removed the compression of the binary and made a new release (0.7.7).
See here for the virustotal report: https://www.virustotal.com/gui/file/0443a5044b301e96cb2c0afb318a663d21aae23979da7265d49eb47f0ae9868c/detection

Thank you for the heads up! I sure do not want to have people thinking I am putting malware on peoples servers.

**Comment by TauNeutrino** [comment]
Thanks for all your effort and quick response! I really appreciate that!
As for the file size: that is of no concern for me. Even if it would be 100 times bigger, I would prefer it to a file that generates false positive virus alerts.
Keep up your incredible work! Thanks!
