### ISSUE TITLE
Any plan to support CR3?

### ISSUE THREAD

**Issue by potato1992** [ariselseng/camerarawpreviews#55]
Any plan to support the new Canon format, .CR3?

**Comment by ariselseng** [comment]
CR3 should work already, as long as it has a built in preview and exiftool can extract it.

**Comment by fabrees** [comment]
I can confirm that CR3 is working for me. But I do not see the extension working with cr3. Is the extension case sensitive?

**Comment by potato1992** [comment]
Thanks, indeed it works, the extension was disabled by nextcloud somehow...> CR3 should work already, as long as it has a built in preview and exiftool can extract it.

**Comment by potato1992** [comment]
I have tried changing .CR3 into .cr3, and it still works. I am using nextcloud19
> I can confirm that CR3 is working for me. But I do not see the extension working with cr3. Is the extension case sensitive?

**Comment by fabrees** [comment]
Ok, also cr3 works. Has to be some differences for already existing files versus new uploads. My existing RAW files are not recognized as pictures and there will be also no preview available.

**Comment by potato1992** [comment]
> 
> 
> Ok, also cr3 works. Has to be some differences for already existing files versus new uploads. My existing RAW files are not recognized as pictures and there will be also no preview available.

Hi, I have faced exactly the same issue, as you referred, it seems only works with newly added cr3 file, thus I have tried 
```
 php occ files:scan --all
```
or with www-data account if apache is started with www-data 
```
sudo -u www-data php occ files:scan --all
```
And it works, all existing cr3 file can be recognized with preview.

**Comment by ariselseng** [comment]
nextcloud caches (forever) preview results so a full scan after installing this app is a good idea.

I have a branch where I test deleting previews to fix this in a more elegant way, but it is not safe to use yet: https://github.com/ariselseng/camerarawpreviews/pull/52

I am closing this now as there does seem to be any problem here.
