### ISSUE TITLE
Mobile app preview?

### ISSUE THREAD

**Issue by anaxmedia** [ariselseng/camerarawpreviews#56]
Hi there. Love this app! Should it work in the official Nextcloud IOS app? When I click on a RAW photo in the mobile app it downloads it instead of opening the preview.

**Comment by ariselseng** [comment]
It should yes. I have never tested the ios app, but it should work like the android app. Can you make a test with android on the same image?

**Comment by ariselseng** [comment]
@anaxmedia I just tested this on a ios device. It downloads the file but actually shows the preview ( I think) generated with this app.
Feel free to open an issue on https://github.com/nextcloud/ios
