### ISSUE TITLE
Don't work RAW images preview 

### ISSUE THREAD

**Issue by Geradot** [ariselseng/camerarawpreviews#58]
Updated to version 20.0.2, but for several major versions the preview of RAW images does not work ...
Maybe it's some kind of cache? Reinstalled the application, didn't help.
Can you help me?

**Comment by ariselseng** [comment]
Try to find anything in the logs and also rescan the files with the occ command.

**Comment by Geradot** [comment]
>Try to find anything in the logs

This is what is written in the logs when I turn on this extension (I cannot keep it turned on for a long time, since the RAM is overloaded and I have to reboot the server)
![Screenshot_20201125_112149](https://user-images.githubusercontent.com/16444502/100208507-7ba08900-2f11-11eb-9638-b3c983ceabf3.png)



> also rescan the files with the occ command

Of course, I will try to do this, but it is unlikely that it will bring a positive result. If there is anything significant, I will let you know in this regard.

**Comment by ariselseng** [comment]
Is there anything in the logs with camera raw preview and also things with error or warning?

**Comment by Geradot** [comment]
> Is there anything in the logs with camera raw preview and also things with error or warning?

As soon as I turn on your add-on, the log is filled with the entries shown in the screenshot. This is just a part that fit on one screen without scrolling. Below are the records of the same type. No entries with the ERROR level were found, there are only INFO and DEBUG.

**Comment by ariselseng** [comment]
@Geradot info and debug is nothing to worry about. I would set the level to warnings and errors if I where you.

**Comment by Geradot** [comment]
> @Geradot info and debug is nothing to worry about. I would set the level to warnings and errors if I where you.

I understand. But what else can I do to give you the information you need? After all, your add-on does not work for me until now

**Comment by ariselseng** [comment]
What server configuration do you use? Like php version, os version , webserver, etc.

**Comment by Geradot** [comment]
**Operating system:** Linux 5.4.78-1-MANJARO #1 SMP PREEMPT Wed Nov 18 21:31:46 UTC 2020 x86_64

**Webserver:** Apache/2.4.46 (Unix) PHP/7.4.12 (apache2handler)

**Database:** mysql 10.5.8

**PHP version:** 7.4.12

**Modules loaded:** Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, curl, gd, gmp, iconv, intl, pdo_mysql, zip, apcu, imagick, memcached, Zend OPcache

**Comment by Geradot** [comment]
Here is the configuration of another server where your add-on is running successfully. As you can see, the difference is absolutely minimal.

**Operating system:** Linux 5.4.78-1-MANJARO #1 SMP PREEMPT Wed Nov 18 21:31:46 UTC 2020 x86_64

**Webserver:** Apache/2.4.46 (Unix) PHP/7.4.12 (apache2handler)

**Database:** mysql 10.5.8

**PHP version:** 7.4.12

**Modules loaded:** Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, curl, gd, gmp, iconv, imap, intl, pdo_mysql, zip, apcu, imagick, memcache, Zend OPcache

**Comment by ariselseng** [comment]
Have you attempted to uploaded a new raw file which you can be certain has not been processed before. (There is some caching going on that can interfere).
If you reuploaded a raw file with a new name that would be a good test to check for that.

**Comment by Geradot** [comment]
After updating the add-on, everything worked! Thanks!
