### ISSUE TITLE
Previews are not generated on Hetzner Storage Share instance

### ISSUE THREAD

**Issue by Ch00k** [ariselseng/camerarawpreviews#59]
I use a Hetzner Storage Share, which is essentially a managed NextCloud deployment, which I have full admin access to (web UI only, no server or database access). I installed the app, uploaded one NEF file, but the preview did not get generated.

I double-checked with Hetzner support, and they claim that both imagick and gd modules are enabled in PHP. I also don't see anything in Nextcloud logs in web UI.

Is there anything else I might be missing? What are the ways to debug this further?

**Comment by ariselseng** [comment]
@Ch00k Check your nextcloud logs. Look for errors and camerarawpreviews.

Also, make sure your NEF file actually has previews embedded in it. You can check that with exiftool on you local machine:

```exiftool  -json -preview:all FILEPATH```

Also do you know which distro/os is hosting it?

**Comment by Ch00k** [comment]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/230214/100718635-db88ab00-33bb-11eb-9908-02ea7db59b96.png">
These are all the logs I got since the inception of my Nextcloud instance.

The `exiftool` shows that there is preview (as far as I can tell):

```
$ exiftool -json -preview:all Downloads/DSC_0125.NEF
[{
  "SourceFile": "Downloads/DSC_0125.NEF",
  "JpgFromRaw": "(Binary data 1373729 bytes, use -b option to extract)",
  "OtherImage": "(Binary data 922292 bytes, use -b option to extract)",
  "PreviewImage": "(Binary data 141163 bytes, use -b option to extract)",
  "ThumbnailTIFF": "(Binary data 57816 bytes, use -b option to extract)"
}]
$
```

**Comment by ariselseng** [comment]
Thanks. The file should have previews yes.
Can you check if the exceptions we see in the logs is triggered when you upload a new raw file?
If there is an exception, that could stop preview generation.

**Comment by Ch00k** [comment]
No, those two error log entries were unrelated to file upload, and new upload does not trigger any errors.

I can ask support to have a look at server-side logs. Do you have a clue where and what to look for exactly?

**Comment by ariselseng** [comment]
You can ask if they allow shell_exec() in php. Which is required.

**Comment by ariselseng** [comment]
The exiftool in the vendors folder also needs to be executable. exiftool and exiftool.bin. but they should be if they have not touched the files after install.

**Comment by Ch00k** [comment]
Wouldn't the app raise exceptions if either `shell_exec()` is not allowed or `exiftool` cannot be executed?

**Comment by ariselseng** [comment]
You are probably right.

**Comment by Ch00k** [comment]
I asked about `shell_exec()` anyway.

**Comment by Ch00k** [comment]
They are saying that `shell_exec` is not available. It's weird that I am not seeing any errors in the log though...

**Comment by Ch00k** [comment]
I cancelled my Hetzner subscription because it is quite useless without this app working. I am still curious to know why the app does not raise any exceptions when it cannot do `shell_exec()`, but you can feel free to close this issue.

**Comment by leowenlu** [comment]
Self hosted, and got the following error, rhel8 , /usr/share/nginx/nextcloud/apps/camerarawpreviews/vendor/exiftool/exiftool/exiftool.bin -json -preview:all -FileType '/usr/share/nginx/nextcloud/data/admin/files/Photos/_DSC1235.NEF'
[{
  "SourceFile": "/usr/share/nginx/nextcloud/data/admin/files/Photos/_DSC1235.NEF",
  "JpgFromRaw": "(Binary data 602063 bytes, use -b option to extract)",
  "PreviewImage": "(Binary data 113463 bytes, use -b option to extract)",
  "ThumbnailTIFF": "(Binary data 57816 bytes, use -b option to extract)",
  "FileType": "NEF"
}]

The error I can see is, any idea? what shall I do to fix it?

usr/share/nginx/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php - line 111:

OCA\CameraRawPreviews\RawPreviewBase->getBestPreviewTag()

/usr/share/nginx/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php - line 61:

OCA\CameraRawPreviews\RawPreviewBase->getResizedPreview()

/usr/share/nginx/nextcloud/apps/camerarawpreviews/lib/RawPreviewIProviderV2.php - line 25:

OCA\CameraRawPreviews\RawPreviewBase->getThumbnailInternal()

/usr/share/nginx/nextcloud/lib/private/Preview/GeneratorHelper.php - line 63:

OCA\CameraRawPreviews\RawPreviewIProviderV2->getThumbnail()

/usr/share/nginx/nextcloud/lib/private/Preview/Generator.php - line 244:

OC\Preview\GeneratorHelper->getThumbnail()

/usr/share/nginx/nextcloud/lib/private/Preview/Generator.php - line 140:

OC\Preview\Generator->getMaxPreview()

/usr/share/nginx/nextcloud/lib/private/Preview/Generator.php - line 109:

OC\Preview\Generator->generatePreviews()

/usr/share/nginx/nextcloud/lib/private/PreviewManager.php - line 190:

OC\Preview\Generator->getPreview()

/usr/share/nginx/nextcloud/core/Controller/PreviewController.php - line 170:

OC\PreviewManager->getPreview()

/usr/share/nginx/nextcloud/core/Controller/PreviewController.php - line 143:

OC\Core\Controller\PreviewController->fetchPreview()

/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

OC\Core\Controller\PreviewController->getPreviewByFileId()

/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

OC\AppFramework\Http\Dispatcher->executeController()

/usr/share/nginx/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch()

/usr/share/nginx/nextcloud/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main()

/usr/share/nginx/nextcloud/lib/base.php - line 1008:

OC\Route\Router->match()

/usr/share/nginx/nextcloud/index.php - line 37:

OC::handleRequest()

**Comment by ariselseng** [comment]
@leowenlu Please open a new issue about this. I am quite busy right with moving into a new house so I might not respond right away.

**Comment by ariselseng** [comment]
Closing this as there is nothing we can do here.
