### ISSUE TITLE
error with RAW NEF file error

### ISSUE THREAD

**Issue by leowenlu** [ariselseng/camerarawpreviews#60]
Self hosted, and got the following error, rhel8 , /usr/share/nginx/nextcloud/apps/camerarawpreviews/vendor/exiftool/exiftool/exiftool.bin -json -preview:all -FileType '/usr/share/nginx/nextcloud/data/admin/files/Photos/_DSC1235.NEF'
[{
"SourceFile": "/usr/share/nginx/nextcloud/data/admin/files/Photos/_DSC1235.NEF",
"JpgFromRaw": "(Binary data 602063 bytes, use -b option to extract)",
"PreviewImage": "(Binary data 113463 bytes, use -b option to extract)",
"ThumbnailTIFF": "(Binary data 57816 bytes, use -b option to extract)",
"FileType": "NEF"
}]

The error I can see is, any idea? what shall I do to fix it?

usr/share/nginx/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php - line 111:

OCA\CameraRawPreviews\RawPreviewBase->getBestPreviewTag()

/usr/share/nginx/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php - line 61:

OCA\CameraRawPreviews\RawPreviewBase->getResizedPreview()

/usr/share/nginx/nextcloud/apps/camerarawpreviews/lib/RawPreviewIProviderV2.php - line 25:

OCA\CameraRawPreviews\RawPreviewBase->getThumbnailInternal()

/usr/share/nginx/nextcloud/lib/private/Preview/GeneratorHelper.php - line 63:

OCA\CameraRawPreviews\RawPreviewIProviderV2->getThumbnail()

/usr/share/nginx/nextcloud/lib/private/Preview/Generator.php - line 244:

OC\Preview\GeneratorHelper->getThumbnail()

/usr/share/nginx/nextcloud/lib/private/Preview/Generator.php - line 140:

OC\Preview\Generator->getMaxPreview()

/usr/share/nginx/nextcloud/lib/private/Preview/Generator.php - line 109:

OC\Preview\Generator->generatePreviews()

/usr/share/nginx/nextcloud/lib/private/PreviewManager.php - line 190:

OC\Preview\Generator->getPreview()

/usr/share/nginx/nextcloud/core/Controller/PreviewController.php - line 170:

OC\PreviewManager->getPreview()

/usr/share/nginx/nextcloud/core/Controller/PreviewController.php - line 143:

OC\Core\Controller\PreviewController->fetchPreview()

/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

OC\Core\Controller\PreviewController->getPreviewByFileId()

/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

OC\AppFramework\Http\Dispatcher->executeController()

/usr/share/nginx/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch()

/usr/share/nginx/nextcloud/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main()

/usr/share/nginx/nextcloud/lib/base.php - line 1008:

OC\Route\Router->match()

/usr/share/nginx/nextcloud/index.php - line 37:

OC::handleRequest()

**Comment by leowenlu** [comment]
I know you are currently quite busy, is there anything I can do to help troubleshooting?

**Comment by ariselseng** [comment]
if you know php you can check if you are allowed to use shell_exec().

**Comment by leowenlu** [comment]
sorry for the late reply, shell_exec() worked as expected.
test.php
<?php
$output = shell_exec('ls -lart');
echo "<pre>$output</pre>";
?>

I can list contents in nextcloud root folder.

**Comment by ariselseng** [comment]
@leowenlu Did you figure this out?
Now when I see the logs you were posting there seems to be missing something from the stack trace. Do you see any exception?

**Comment by leowenlu** [comment]
do you mean the exception like the below? or what exactly is the exception? or let me know where I can get the log for you.

eviews | Exception: Unable to find preview data: /usr/share/nginx/nextcloud/apps/camerarawpreviews/vendor/exiftool/exiftool/exiftool.bin -json -preview:all -FileType '/usr/share/nginx/nextcloud/data/admin/files/Photos/_DSC1235.NEF' ->
-- | --

**Comment by leowenlu** [comment]
any clue?

/usr/share/nginx/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php - line 111:

OCA\CameraRawPreviews\RawPreviewBase->getBestPreviewTag()

/usr/share/nginx/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php - line 61:

OCA\CameraRawPreviews\RawPreviewBase->getResizedPreview()

/usr/share/nginx/nextcloud/apps/camerarawpreviews/lib/RawPreviewIProviderV2.php - line 25:

OCA\CameraRawPreviews\RawPreviewBase->getThumbnailInternal()

/usr/share/nginx/nextcloud/lib/private/Preview/GeneratorHelper.php - line 63:

OCA\CameraRawPreviews\RawPreviewIProviderV2->getThumbnail()

/usr/share/nginx/nextcloud/lib/private/Preview/Generator.php - line 244:

OC\Preview\GeneratorHelper->getThumbnail()

/usr/share/nginx/nextcloud/lib/private/Preview/Generator.php - line 140:

OC\Preview\Generator->getMaxPreview()

/usr/share/nginx/nextcloud/lib/private/Preview/Generator.php - line 109:

OC\Preview\Generator->generatePreviews()

/usr/share/nginx/nextcloud/lib/private/PreviewManager.php - line 190:

OC\Preview\Generator->getPreview()

/usr/share/nginx/nextcloud/core/Controller/PreviewController.php - line 170:

OC\PreviewManager->getPreview()

/usr/share/nginx/nextcloud/core/Controller/PreviewController.php - line 143:

OC\Core\Controller\PreviewController->fetchPreview()

/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

OC\Core\Controller\PreviewController->getPreviewByFileId()

/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

OC\AppFramework\Http\Dispatcher->executeController()

/usr/share/nginx/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch()

/usr/share/nginx/nextcloud/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main()

/usr/share/nginx/nextcloud/lib/base.php - line 1008:

OC\Route\Router->match()

/usr/share/nginx/nextcloud/index.php - line 37:

OC::handleRequest(

**Comment by ariselseng** [comment]
@leowenlu Just a thought. Do you have local files or do you use some kind of external storage?

**Comment by leowenlu** [comment]
local files, no external storage.

**Comment by ariselseng** [comment]
@leowenlu 
Sorry for super late reply. Do you still have this issue or can I close this?

**Comment by ariselseng** [comment]
@leowenlu Closing this for now. Please reopen this issue if you want to continue this debugging.
