### ISSUE TITLE
Make SRW work please

### ISSUE THREAD

**Issue by matlinski** [ariselseng/camerarawpreviews#62]
Hi, this wouldn't probably be a very high priority task but I would appreciate it a lot, I'm hosting my own cloud and it's perfect. Except can't view the SRW file, CRW works great thanks to you but I still have a lot of SRW files, and sadly I have to download them which is not ideal.

**Comment by ariselseng** [comment]
If CRW works for you, but SRW does not, I bet your SRW files does not have any preview embedded. Could you upload a sample so I could have a look?

**Comment by matlinski** [comment]
Hello Ari, thank you for such quick reply, below I'm sharing with you one of the files that I'm self hosting on Nextcloud.
https://matlinski.devs.rest/s/iGJ2f2TMmd5r8DC

**Comment by ariselseng** [comment]
That file worked fine for me. Can you try to rename it locally on your machine and then reupload it as a new file? Will the preview work then? It may be some caching issue.

**Comment by matlinski** [comment]
Hello Ari, you were right! It works! Now the question is how do I make it work without reuploading all the files. Renaming or moving them around didn't help.

**Comment by ariselseng** [comment]
I think you can run occ files:scan. I have a branch here on GitHub to delete nextcloud preview cache but it is not stable yet.

**Comment by matlinski** [comment]
Ok, it worked! Thanks for your time Ari! We can close this issue.
