### ISSUE TITLE
Does not support Apple ProRAW files

### ISSUE THREAD

**Issue by StarKfeirchris** [ariselseng/camerarawpreviews#63]
Apple ProRAW (.dng) files not loading, but Sony RAW (.arw) files can loading, 
will it be supported in the future?

Apple ProRAW
https://i.imgur.com/LNLdjVy.png

Sony RAW
https://i.imgur.com/vcQJn3I.png

**Comment by ariselseng** [comment]
I think exiftool does not support it: https://exiftool.org/#supported
Maybe it will work in the future. Can you upload a sample so i can have a look?

**Comment by StarKfeirchris** [comment]
Sample:
https://www.mediafire.com/file/bxxpkkie7e1oszu/Apple_ProRAW_sample.7z/file

There are two files in this 7z file, `IMG_4378.DNG` is the original unedited RAW file, and `IMG_4378-01.DNG` is the RAW file edited with the "Photos" app, `IMG_4378.DNG` can review, but `IMG_4378-01.DNG` can not review.

**Comment by ariselseng** [comment]
This image only has depth image data and no preview so I am afraid I cannot make this work (without generating new preview but that is not something I have done with this app yet).
