### ISSUE TITLE
ARW Preview for Sony Alpha 7 III files is not working

### ISSUE THREAD

**Issue by s-hufschmid** [ariselseng/camerarawpreviews#64]
Sony ARW Preview for Sony Alpha 7 III is not working.
no matter if it is an compressed ARW or uncompressed File.
Installed Nextcloud Version: 20.0.4

**Comment by ariselseng** [comment]
Are other raw files working for you? You can find samples on the web.

**Comment by s-hufschmid** [comment]
Hi !
I checked it with other raw files .. NEF and CR2 ... Didn't work also :-(

**Comment by ariselseng** [comment]
Let me guess. Are you a arm server or snap install?

**Comment by s-hufschmid** [comment]
I'm on a hosted solution on www.hetzner.de.
I will check if it a snap install oder not.. 
What if it is an snap based install  ?

**Comment by ariselseng** [comment]
I think hetzner is blocking shell_exec. There has been others reporting that.

**Comment by ariselseng** [comment]
See here. Same issue: https://github.com/ariselseng/camerarawpreviews/issues/59

**Comment by ariselseng** [comment]
Closing this as there is nothing we can do here I am afraid. At the least there should be a way to detect this so that we can avoid having users installing the app, but I am afraid Nextcloud/Owncloud do not have a check for this.
