### ISSUE TITLE
NC21 previews not showing

### ISSUE THREAD

**Issue by michaave** [ariselseng/camerarawpreviews#67]
No previews in nextcloud, logs show: 

Exception: Unable to find preview data: /var/www/html/apps/camerarawpreviews/vendor/exiftool/exiftool/exiftool.bin -json -preview:all -FileType '/media/myCloudDrive/NextCloudData/michaave/files/Photos/Phone camera/2021/04/IMG_20210401_170452.dng' -> [{ "SourceFile": "/media/myCloudDrive/NextCloudData/michaave/files/Photos/Phone camera/2021/04/IMG_20210401_170452.dng", "FileType": "DNG" }]

I do have perl installed, and I tested by copying the dng file to the same folder as exiftool.bin and executing the command from exiftool folder: perl ./exiftool.bin -json -preview:all -FileType IMG_20210401_170452.dng

It seemed to succeed, saying "you have new mail in /var/mail/www"

**Comment by ariselseng** [comment]
Hello,
Thanks for reporting.

Two things:
"you have new mail in /var/mail/www" has actually nothing to do with the command you were typing. It is the shell telling you that you have an email. This might be a failing cron-job or something. You can check in /var/mail/www.

The exception indicates that there is no preview data inside the exif data. This app only extracts previews and does not actually convert the raw image:
```json
 [{ "SourceFile": "/media/myCloudDrive/NextCloudData/michaave/files/Photos/Phone camera/2021/04/IMG_20210401_170452.dng", "FileType": "DNG" }]

**Comment by michaave** [comment]
Ah, so these DNG files don't contain usable preview data for the plugin to use?

**Comment by ariselseng** [comment]
That is correct.
