### ISSUE TITLE
Application is not setup via query() but directly at <<closure>>

### ISSUE THREAD

**Issue by adripo** [ariselseng/camerarawpreviews#68]
Hello,

After enabling debug on Nextcloud 21, I get this error in the logs.

```
[camerarawpreviews] Error: RuntimeException: App class OCA\CameraRawPreviews\AppInfo\Application is not setup via query() but directly at <<closure>>

0. /var/www/html/custom_apps/camerarawpreviews/lib/AppInfo/Application.php line 16
   OCP\AppFramework\App->__construct("camerarawpreviews")
1. /var/www/html/custom_apps/camerarawpreviews/appinfo/app.php line 3
   OCA\CameraRawPreviews\AppInfo\Application->__construct()
2. /var/www/html/lib/private/legacy/OC_App.php line 295
   require_once("/var/www/html/c ... p")
3. /var/www/html/lib/private/legacy/OC_App.php line 177
   OC_App::requireAppFile("camerarawpreviews")
4. /var/www/html/lib/private/legacy/OC_App.php line 137
   OC_App::loadApp("camerarawpreviews")
5. /var/www/html/lib/base.php line 979
   OC_App::loadApps()
6. /var/www/html/index.php line 37
   OC::handleRequest()

GET /apps/logreader/poll?lastReqId=clHlz4Uvqd2OhMhN35ny
from 192.168.80.2 by at 2021-04-22T22:36:00+00:00
```

As I read on [this issue](https://github.com/nextcloud/maps/issues/384) for calendar the solution should be something like [this](https://github.com/nextcloud/calendar/pull/1958/files#diff-079bbe455bfa9aeaf363ae1bc6415ba0R25).

**Comment by ariselseng** [comment]
Thank you for the heads up. I have not upgraded to 21 myself yet.

**Comment by adripo** [comment]
It can be tried in a docker container running v21.
Otherwise I can test it myself. I am not sure the issue is solved by simply changing that row or other things need to be changed. If it is just that I can do a pr.

**Comment by ariselseng** [comment]
This is should better in latest release. Still other debug notices though.
