### ISSUE TITLE
LOVE IT -- but CR3 preview is badly needed :)

### ISSUE THREAD

**Issue by jblax07** [ariselseng/camerarawpreviews#69]
Really appreciative for what you've done and just want to encourage support for CR3. We've been updating our cameras and really would like to see Canon's Cr3 files on the server :) 

MEGA THANKS!

**Comment by ariselseng** [comment]
@jblax07

Thank you for your kind words.

This only supports raw files that have previews embedded in them, including CR3. Some cameras do not embed previews and those will not work with this app.

Some image library applications like Lightroom add these previews and I would recommend something like that as a workaround.

Hope it works out :)
