### ISSUE TITLE
Unable to find preview data (.ARW)

### ISSUE THREAD

**Issue by HeyWatchOutDude** [ariselseng/camerarawpreviews#70]
Hi,

is there a known problem with NC version "21.0.2"?

Because I'm getting a lot of errors while creating previews of an ".ARW" file.

Error
camerarawpreviews
2021-06-06T23:16:46+0200
Exception: Unable to find preview data: /var/www/nextcloud/apps/camerarawpreviews/vendor/exiftool/exiftool/exiftool.bin -json -preview:all -FileType '/media/cloud/nextcloud/user1/files/Freigabe/Folder1/21-06-06 14-29-16 4860.arw' -> [{ "SourceFile": "/media/cloud/nextcloud/user1/files/Freigabe/Folder1/21-06-06 14-29-16 4860.arw", "FileType": "JPEG" }]

Any idea? (App is up to date)

**Comment by ariselseng** [comment]
Not that i know of. It would help if you could upload a sample for me to test.

**Comment by HeyWatchOutDude** [comment]
Sure, here is an example:

https://drive.google.com/drive/folders/1X_cm6-jDfOfpYqLaoaJIEfQAdONrA5o3

**Comment by ariselseng** [comment]
@HeyWatchOutDude That files works fine on my install.
Are you sure that the file you sent me and the file provided in the example "21-06-06 14-29-16 4860.arw" is from the exact same setup? The log example shows that the "21-06-06 14-29-16 4860.arw" is actually detected as a jpeg. I have never seen that. But the test ile you sent me is not, that is a normal raw file.

The app is using "exiftool" to do the extraction of the preview inside the file and you can debug for yourself with this command:

exiftool -json -preview:all -FileType -FileType DSC04915.ARW

The output will should be:
```shell
[{
  "SourceFile": "DSC04915.ARW",
  "PreviewImage": "(Binary data 509182 bytes, use -b option to extract)",
  "ThumbnailImage": "(Binary data 10666 bytes, use -b option to extract)",
  "FileType": "ARW"
}]

**Comment by HeyWatchOutDude** [comment]
I have checked it again ... somehow when I open an .ARW file I'm getting that preview:

https://imgur.com/a/obdddvH

After clicking on the three dots and "Open with" the image gets successfully downloaded and I can view the image + preview:

https://imgur.com/a/jv40Kpw

https://imgur.com/a/qE3SJot

Via the web I only get an error message:
(Error while loading)

https://imgur.com/a/Jn6UoIC

**Comment by HeyWatchOutDude** [comment]
Ok I think it's a nextcloud bug ....

When I open the apple photos app and choose the pictures from their to upload it to the nextcloud ... everything is working fine. (File type: *.ARW)

In comparison when I open the nextcloud app and choose upload picture and videos ... the files somehow are getting corrupted. 
(File type: *.arw)

Could you please try to replace it on your site?

**Comment by ariselseng** [comment]
@HeyWatchOutDude Hi,
What do you mean by "replace it"?

**Comment by HeyWatchOutDude** [comment]
I found the issue ... somehow when the files (photos) got imported from a sd card directly to an iOS device ... the files are getting corrupted.

I think you can close the issue, thanks for your time & help!

**Comment by ariselseng** [comment]
Glad you figured it out! Closing.
