### ISSUE TITLE
Support for Apple DNG files

### ISSUE THREAD

**Issue by frieck** [ariselseng/camerarawpreviews#72]
Hello!

iPhone have now support for taking raw images (saved as .dng files) but the preview is not generated for it.
Is there a fix for that?

Thanks

**Comment by ariselseng** [comment]
@frieck I am afraid there is not. I have very limited time. Fixing this would involve starting to generate previews directly from raw instead of using exiftool to extract existing previews. There is a big difference in amount of work in these two different approaches.
