### ISSUE TITLE
Camera Raw Previews stop working when pdlib is enabled

### ISSUE THREAD

**Issue by guydelarea** [ariselseng/camerarawpreviews#75]
Hey!

i am using Nextcloud 22.1.1 on Ubuntu server (20.04) running on nginx, and when i am trying to run this app with the **pdlib** php extension because of the [face recognition app](https://github.com/matiasdelellis/facerecognition) and when i do i`am getting an error loading RAW image files.

when i disable [pdlib.so](https://github.com/goodspb/pdlib.git) in the php.ini the app goes back to work fine.

Log File:
`[camerarawpreviews] ImagickException: Error: negative or zero image size /tmp/8773d2d64c2a41c4454378729a238edb.jpg  error/image.c/CloneImage/794`

`GET /core/preview?fileId=3676487&c=3eb0599d7b2eb1d8f6cebd1fe67a41ca&x=250&y=250&forceIcon=0&a=0
from XX.X.XX.XXX.XX by guydelarea at 2021-10-07T21:15:35+00:00`

i understand that the pdlib library interfere with the image processing of this app but didn't manage a way to make them both work at the same time, i use alot of RAW sony files (ARW) and this app is a life safer.

**Comment by ariselseng** [comment]
Hmm, i am not sure we can do much here. Maybe we could have setting to force using GD instead of imagick. Your problem sounds like it is interfering with imagick.
