### ISSUE TITLE
can support sony a7m3 & a7r4 & a7c arw file?

### ISSUE THREAD

**Issue by 3egirlsdream** [ariselseng/camerarawpreviews#76]
now just can view a7m2 raw file.

**Comment by ariselseng** [comment]
If you upload an example somewhere I can have a look. There must be a preview embedded in the exif data a d exiftool needs to support extracting it.

**Comment by guydelarea** [comment]
the camera previews is working for my A7R3 and A73 arw files.

**Comment by 3egirlsdream** [comment]
> the camera previews is working for my A7R3 and A73 arw files.

I made a mistake, these cameras were supported, the really question is if the folder name is Chinese, the raw files will can't view in this folder.  web, android, ios client are same.

**Comment by ariselseng** [comment]
@3egirlsdream Alright, closing this. Please follow up in the other thread.
