### ISSUE TITLE
 Unable to find preview data: canon .CR2

### ISSUE THREAD

**Issue by DeniGam** [ariselseng/camerarawpreviews#77]
Previews are not shown for *.CR2 files.
Nextcloud: 22.2.0 (in docker based on latest image)
Host system: Ubuntu-server 20.04 LTC

 php --version:
 `PHP 8.0.12 (cli) (built: Oct 21 2021 15:29:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.12, Copyright (c), by Zend Technologies`

apt list --installed | grep imagemagick:
`imagemagick-6-common/now 8:6.9.11.60+dfsg-1.3 all [installed,local]
imagemagick-6.q16/now 8:6.9.11.60+dfsg-1.3 amd64 [installed,local]
imagemagick/now 8:6.9.11.60+dfsg-1.3 amd64 [installed,local]`

`"Exception":"Exception",
      "Message":"Unable to find preview data: /var/www/html/custom_apps/camerarawpreviews/vendor/exiftool/exiftool/exiftool.bin -json -preview:all -FileType '/var/www/html/data/denigam/files/familyShare//Canon EOS 800D/2020.12.16/IMG_1316.CR2' -> ",
      "Code":0` 

[Please see full trace](https://github.com/ariselseng/camerarawpreviews/files/7401132/trace.txt)

**Comment by ariselseng** [comment]
@DeniGam Here is an  example file that you could load through apache:
```php
<?php
$currentLocale = setlocale(LC_ALL, 0);
var_dump($currentLocale);
```
I would really appreciate if you could help me reproduce this.

**Comment by DeniGam** [comment]
Hi @ariselseng . I'm not quite understand where I can locate this file and how I can run it.

**Comment by ariselseng** [comment]
@DeniGam Ah, I would put it in the same folder as the nextcloud files, like  /var/www/html.
 Call it "test.php", and then, depending on your setup, you should be able to reach it by http://YOURNEXTCLOUD/test.php.
Are you using apache? if not, then you might not be able to reach it so easily.

**Comment by DeniGam** [comment]
Ok. It looks like I found another way - I modified status.php, and add 'currentLocale' => setlocale(LC_ALL, 0), and then I call /status.php.
The result:
`{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"22.2.0.2","versionstring":"22.2.0","edition":"","productname":"Nextcloud","extendedSupport":false,"currentLocale":"C"}`
I know that this is not exactly you've asked me, but when I try to put the file to the directory and call it - it always tries to redirect me to HTTPS protocol and returns SSL-protocol error. So I guess my option is in general the same.

**Comment by ariselseng** [comment]
@DeniGam Thank you! I had the same value as you.
Could you send me a zip file with a folder with the special characters an a raw file? I tried creating a folder named "Фото" and putting a raw file into it, but it just worked :/

**Comment by DeniGam** [comment]
You may download this here: https://drive.google.com/file/d/1Xe1vIrGkIsM39fqqrVLEQ4rXpUiu142W/view?usp=sharing
And one more thing, possible I know why it may works for you - NC uses some cache for created previews (and looks like it attached to file itself, not to path). That's why if I initially rename the folder to English, than open preview (it works fine), and then rename it to Russian - the preview will work for this file

**Comment by ariselseng** [comment]
A fix is coming soon. I was able to reproduce it now reliably.

**Comment by ariselseng** [comment]
@DeniGam Please try version 0.7.13, should be available in your Nextcloud in an hour or less.

**Comment by DeniGam** [comment]
Yes, now it works! Thank you a lot for your help and for your time!

**Comment by ariselseng** [comment]
Finally! :D
