### ISSUE TITLE
[BUG] Can't view raw files if the folder name is Chinese

### ISSUE THREAD

**Issue by 3egirlsdream** [ariselseng/camerarawpreviews#78]
## how to reappear
- download raw files support plugin
- create a folder named by Chinese
- upload a sony camera raw file into the folder
- then u will see the file cant view not only web, but also android ios client too.

**Comment by ariselseng** [comment]
@3egirlsdream Multiple people have reported this without me figuring out how to reproduce it. On my system chinese characters works great. Could you provide me with some details about the web server and locale setup?

**Comment by ariselseng** [comment]
@3egirlsdream Here is an  example file that you could load through apache:
```php
<?php
$currentLocale = setlocale(LC_ALL, 0);
var_dump($currentLocale);
```
I need the output of this so I can try to reproduce the issue locally.

**Comment by ariselseng** [comment]
@3egirlsdream Please try version 0.7.13 .

**Comment by ariselseng** [comment]
Closing this. This should be fixed now.
