### ISSUE TITLE
Preview not working ( .dng )

### ISSUE THREAD

**Issue by gmeks** [ariselseng/camerarawpreviews#84]
The .dng file is generated by andriod app [opencamera](https://sourceforge.net/projects/opencamera/) , the web interface just remains spinning like its waiting.

Download link to image: https://cloud.thexsoft.com/index.php/s/WZAoGDbNx4R4ZGt

PHP INFO:
Version: 8.0.22
Memory limit: 4 GB
Max execution time: 3600
Upload max size: 4 GB
Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, Phar, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, pdlib, Zend OPcache

Log:
`{"reqId":"kuPSlz5cFDPmPix1qPza","level":3,"time":"2022-08-15T10:38:19+00:00","remoteAddr":"141.0.78.50","user":"eks","app":"camerarawpreviews","method":"GET","url":"/index.php/core/preview?fileId=5636119&x=250&y=250","message":"Unable to find preview data: /var/www/html/custom_apps/camerarawpreviews/vendor/exiftool/exiftool/exiftool.bin -json -preview:all -FileType '/var/ncdata/ncdata/eks/files/Temp/IMG_20220720_142311.dng' -> [{\n  \"SourceFile\": \"/var/ncdata/ncdata/eks/files/Temp/IMG_20220720_142311.dng\",\n  \"FileType\": \"DNG\"\n}]\n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.4.1","exception":{"Exception":"Exception","Message":"Unable to find preview data: /var/www/html/custom_apps/camerarawpreviews/vendor/exiftool/exiftool/exiftool.bin -json -preview:all -FileType '/var/ncdata/ncdata/eks/files/Temp/IMG_20220720_142311.dng' -> [{\n  \"SourceFile\": \"/var/ncdata/ncdata/eks/files/Temp/IMG_20220720_142311.dng\",\n  \"FileType\": \"DNG\"\n}]\n","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/camerarawpreviews/lib/RawPreviewBase.php","line":110,"function":"getBestPreviewTag","class":"OCA\\CameraRawPreviews\\RawPreviewBase","type":"->","args":["/var/ncdata/ncdata/eks/files/Temp/IMG_20220720_142311.dng"]},{"file":"/var/www/html/custom_apps/camerarawpreviews/lib/RawPreviewBase.php","line":60,"function":"getResizedPreview","class":"OCA\\CameraRawPreviews\\RawPreviewBase","type":"->","args":["/var/ncdata/ncdata/eks/files/Temp/IMG_20220720_142311.dng",4096,4096]},{"file":"/var/www/html/custom_apps/camerarawpreviews/lib/RawPreviewIProviderV2.php","line":25,"function":"getThumbnailInternal","class":"OCA\\CameraRawPreviews\\RawPreviewBase","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},4096,4096]},{"file":"/var/www/html/lib/private/Preview/GeneratorHelper.php","line":65,"function":"getThumbnail","class":"OCA\\CameraRawPreviews\\RawPreviewIProviderV2","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},4096,4096]},{"file":"/var/www/html/lib/private/Preview/Generator.php","line":335,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->","args":[{"__class__":"OCA\\CameraRawPreviews\\RawPreviewIProviderV2"},{"__class__":"OC\\Files\\Node\\File"},4096,4096]},{"file":"/var/www/html/lib/private/Preview/Generator.php","line":159,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"},{"__class__":"OC\\Files\\Node\\File"},"image/x-dcraw",""]},{"file":"/var/www/html/lib/private/Preview/Generator.php","line":111,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},[[250,250,true,"fill"]],"image/x-dcraw"]},{"file":"/var/www/html/lib/private/PreviewManager.php","line":212,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},250,250,true,"fill",null]},{"file":"/var/www/html/core/Controller/PreviewController.php","line":169,"function":"getPreview","class":"OC\\PreviewManager","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},250,250,true,"fill"]},{"file":"/var/www/html/core/Controller/PreviewController.php","line":142,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},250,250,false,true,"fill"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[5636119,250,250,false,true,"fill"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\PreviewController"},"getPreviewByFileId"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\PreviewController"},"getPreviewByFileId"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\PreviewController","getPreviewByFileId",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["core.Preview.getPreviewByFileId"]]},{"file":"/var/www/html/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/core/preview"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/camerarawpreviews/lib/RawPreviewBase.php","Line":202,"CustomMessage":"--"},"id":"62fa225325d52"}
`

**Comment by ariselseng** [comment]
Your file does not contain a preview.

**Comment by ariselseng** [comment]
> Hey, I know this is an old issue but I'm not too familiar with RAWs and I'm also an OpenCamera user with the same issue.
> 
> Does this mean that DNG files embed previews, and this app only extracts the preview from DNG files with previews, instead of generating thumbnails?

Yes. This app only extracts the embedded preview. Actually generating previews reliably across different cameras and setups requires a lot more work to get good results.
