### ISSUE TITLE
No CR3 Previews

### ISSUE THREAD

**Issue by xeonixo** [ariselseng/camerarawpreviews#85]
Hey,

i am unable to generate CR previews... Files are ~ 30 MB

Envoirement: Docker on Dedicated Server
Image: official Nextcloud (24.0.4.2) Apache
PHP-v:8.0.22
Raw-Prev-V: 0.8.0

What did i try?
- Force Preview Generation with occ preview:generate-all
- Change to imaginary for previews -> works, but not with cr3

my issue: huge CR3 files without small preview need too much internet (folders are ~ 60 GB) even my 500 Mbit connection is too slow to work efficient

**Just by typing this i found following: CAPS .CR3 are not previewed.... .cr3 are getting a preview....** 

Logs: well... did not found anything inside

**Comment by xeonixo** [comment]
Renamed everything in windows... but its just a workaround

**Comment by ariselseng** [comment]
This is not due renaming of the filename extension, but has with busting the nextcloud file cache. A full rescan of the files would probably do the same. It has todo with Nextcloud caching mimetypes and/or preview information before you installed this app.
