### ISSUE TITLE
Thumbs generate but previews don't

### ISSUE THREAD

**Issue by D34DC3N73R** [ariselseng/camerarawpreviews#86]
I see thumbnails generated, but previews fail to load. These are ARW's from a sony camera. 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/9123670/192850263-06c6524a-3563-4798-805a-addbeffb79a0.png">

<img width="371" alt="image" src="https://user-images.githubusercontent.com/9123670/192850612-79bd60d0-eecb-4737-8c81-6d3d7b30f9bf.png">

<img width="843" alt="image" src="https://user-images.githubusercontent.com/9123670/192857516-127cba51-302b-466b-aea7-26491e045b08.png">

**Comment by ariselseng** [comment]
@D34DC3N73R Are you sure there is preview information in your file? This app only extracts the jpeg already inside the file.

**Comment by ariselseng** [comment]
@D34DC3N73R Also, you could send me a sample file that has this issue and I could see if I can reproduce your issue.

**Comment by D34DC3N73R** [comment]
I sent a sample to your email. I'm sure it used to work because I've previously previewed ARW files from the same camera. Unfortunately, I don't know the exact version it stopped working. Thanks for taking a look!

**Comment by andreybavt** [comment]
Hi, I'm having the same problem but with opening `NEF` files. 
Camera RAW Previews version is 0.8.0
I'm running NextCloud 25.0.1 from TrueNAS.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/7889985/200093666-3699e876-58ef-4a91-85e5-0e3b1d8154cd.png">

Same as above, a thumbnail is created, but when I open a NEF file itself there's an infinite spinner

I'm curious to know about the fix

**Comment by D34DC3N73R** [comment]
I've updated to Nextcloud 24.0.7 and still have the same issue, with CRP v0.8.0. I haven't found a solution yet.

**Comment by andreybavt** [comment]
another strange thing that I noticed: 

when first opening an image that does work, `jpg` for example and then clicking "next" to navigate to NEF the preview does work. But when opening NEF directly it doesn't (infinite spinner)

**Comment by ivan11paths** [comment]
I have the same problem with Olympus RAWs. And I confirm the forward/back operation that @andreybavt comments.

**Comment by ariselseng** [comment]
I am pretty sure this is a regression in the viewer app. Does anyone care to downgrade the viewer app to a known good time/version.

**Comment by jkhsjdhjs** [comment]
Since there haven't been many changes between 24.0.3 and 24.0.4, I'm pretty sure that this commit broke the file handler logic:
https://github.com/nextcloud/viewer/commit/e2c48013628cf19c2519cb2c7efb96014dcdb591

@andreybavt has already created an issue: https://github.com/nextcloud/viewer/issues/1450
