### ISSUE TITLE
[suggestion] Support for CR3-Files

### ISSUE THREAD

**Issue by stull-e** [ariselseng/camerarawpreviews#87]
I am very happy for having found this app. It works like a charm with the CR2-Files of my Canon Eos 70d DSLR. Unfortunately Canon switched to a new file type with its newer camera models. My M50 shoots CR3-Files. As far as I know the relatively new EOS R mirrorless cameras also use the CR3 file type, which seem not to be supported by the app.

Would it be possible to add CR3 support in the app?

**Comment by ariselseng** [comment]
Just make sure the files have a jeg preview embedded and it should work. This app uses exiftool under the hood to extract the preview.

**Comment by stull-e** [comment]
Thanks for the fast answer. Sorry for the duplicate. I'm new to github. Will be checking the 'solved issues' next time.

**Comment by ariselseng** [comment]
No problem! You can also find examples of how to debug a raw file to check (with exiftool) if there is a preview embedded. Feel free to send me an example of a file that does not work and I can check it in my nextcloud if it works for me.
