### ISSUE TITLE
Raw preview problem

### ISSUE THREAD

**Issue by alejandrorr01** [ariselseng/camerarawpreviews#90]
hello
I'm new to nextcloud and I don't know if I'm doing something wrong or if there is a problem in my configuration that doesn't allow the preview to work.

This is the error it sends.

Best regards

[camerarawpreviews] Error: Exception: Unable to find preview data: /var/www/html/nextcloud/apps/camerarawpreviews/vendor/exiftool/exiftool/exiftool.bin -json -preview:all -FileType '/var/www/html /nextcloud/data/Alejandro Reyes/files/CONADE/DSC08255.ARW' -> at <<closure>>

  0. /var/www/html/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php line 110
     OCA\CameraRawPreviews\RawPreviewBase->getBestPreviewTag()
  1. /var/www/html/nextcloud/apps/camerarawpreviews/lib/RawPreviewBase.php line 60
     OCA\CameraRawPreviews\RawPreviewBase->getResizedPreview()
  2. /var/www/html/nextcloud/apps/camerarawpreviews/lib/RawPreviewIProviderV2.php line 25
     OCA\CameraRawPreviews\RawPreviewBase->getThumbnailInternal()
  3. /var/www/html/nextcloud/lib/private/Preview/GeneratorHelper.php line 65
     OCA\CameraRawPreviews\RawPreviewIProviderV2->getThumbnail()
  4. /var/www/html/nextcloud/lib/private/Preview/Generator.php line 343
     OC\Preview\GeneratorHelper->getThumbnail()
  5. /var/www/html/nextcloud/lib/private/Preview/Generator.php line 162
     OC\Preview\Generator->getMaxPreview()
  6. /var/www/html/nextcloud/lib/private/Preview/Generator.php line 114
     OC\Preview\Generator->generatePreviews()
  7. /var/www/html/nextcloud/lib/private/PreviewManager.php line 185
     OC\Preview\Generator->getPreview()
  8. /var/www/html/nextcloud/core/Controller/PreviewController.php line 144
     OC\PreviewManager->getPreview()
  9. /var/www/html/nextcloud/core/Controller/PreviewController.php line 113
     OC\Core\Controller\PreviewController->fetchPreview()
10. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
     OC\Core\Controller\PreviewController->getPreviewByFileId()
11. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
     OC\AppFramework\Http\Dispatcher->executeController()
12. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 172
     OC\AppFramework\Http\Dispatcher->dispatch()
13. /var/www/html/nextcloud/lib/private/Route/Router.php line 298
     OC\AppFramework\App::main()
14. /var/www/html/nextcloud/lib/base.php line 1047
     OC\Route\Router->match()
15. /var/www/html/nextcloud/index.php line 36
     OC::handleRequest()

GET /index.php/core/preview?fileId=1507&c=bf46ea38e648d20780b813cf56458e8f&x=500&y=500&forceIcon=0&a=0

**Comment by ariselseng** [comment]
Hmm. Are you able to upload a sample file for me to check?

**Comment by alejandrorr01** [comment]
Hello, thanks for the support.  

Of course what do you need?

**Comment by ariselseng** [comment]
You can find my email at my github profile. You share me a file which there is no preview for. I can check if there is an embedded preview in it.

**Comment by alejandrorr01** [comment]
Ari Thanks again for your help.

I sent you an email with the information you requested and in it are shared files with which I have had problems.

**Comment by ariselseng** [comment]
Closing this. For other people that got the same problem. This app needs to be white listed in SELINUX.

**Comment by MrRinkana** [comment]
>This app needs to be white listed in SELINUX.

Could you expand on why this is the case? Not many other apps require to be individually whitelisted in SELINUX. It seems that it requires httpd_unified, which is recommended to keep off in the installation docs for nc (except when upgrading) so the only other options seems to be to allow bash specifically on exiftool.bin - is this what you recommend?

Would it work to use ```perl-Image-ExifTool``` (provides exiftool according to dnf) instead of a bundled binary? Would that solve the issue?
