### ISSUE TITLE
Support of .CR3

### ISSUE THREAD

**Issue by georg-mayer** [ariselseng/camerarawpreviews#91]
Hello,

this app is great - thank you for it. 

I now own a Canon R7 and it stores the RAW files in .CR3 format. Is there any plan to support this format as well?

Thanks and cheers,
Georg

**Comment by ariselseng** [comment]
This has been asked before: https://github.com/ariselseng/camerarawpreviews/issues?q=is%3Aissue+CR3+is%3Aclosed

It is supported. The file just needs an embedded preview.
