### ISSUE TITLE
CR3 Raw file from Canon is loop loading and never shown 

### ISSUE THREAD

**Issue by mixmafritz** [ariselseng/camerarawpreviews#99]
Infos : 
Camera RAW Previews 0.8.2
Nextcloud 27.1.0

CR3 Raw file from Canon is loop loading and never shown :
![image](https://github.com/ariselseng/camerarawpreviews/assets/79789667/fa03d567-02a0-4e83-b916-12ce4c11a880)

I delete and reinstall manually this plugin but still not work.

Greetings.

**Comment by mixmafritz** [comment]
EDIT : its loading correctly from official Nextcloud app on android phone but still not working on PC.

**Comment by ariselseng** [comment]
I am afraid this is a bug in the Nextcloud Viewer. There is a draft pull request there that have become stale. Hopefully they will fix it soon.

**Comment by ariselseng** [comment]
Please voice your issue here at the repo for Viewer. The stale PR is here: https://github.com/nextcloud/viewer/pull/1456
